### ISSUE TITLE
Lab #5 review

### ISSUE THREAD

**Issue by igor-leshkevych** [maksymbudzin/article_lab5_flutter#1]
@maksymbudzin I like how you combined your state and fetching data. But you have a couple of minor bugs that must be fixed:
![image](https://user-images.githubusercontent.com/15331006/143271173-5401ab7c-29f8-439d-b617-949864f81747.png)
![image](https://user-images.githubusercontent.com/15331006/143271649-bc4ee57a-da5d-43b7-84ec-97c17299634e.png)
![image](https://user-images.githubusercontent.com/15331006/143271713-7681bb44-867d-49aa-b362-4686cef59c56.png)

Some improvements, to be made:
1.Download this pic and use it as an asset 
![image](https://user-images.githubusercontent.com/15331006/143271851-3ffb1ab2-8a77-40f5-82e7-a0ee9561a7f0.png)
2. Add some possibility to change state from the UI (add article to favorite, hide it from the list, or similar)

Do all that, and you'll have max score

**Comment by maksymbudzin** [comment]
hello, I fixed the bugs you mentioned, I also added a video to the readme
(hide articles from the list)

ср, 24 лист. 2021 о 17:58 Igor ***@***.***> пише:

**Comment by igor-leshkevych** [comment]
@maksymbudzin app still crashes when `urlToImage` is null, adding null checks in all of the places where it's used fixed the problem, but it should be probably done by you, not me. The rest of the app is OK.

Score 15/20
